[project]
name = "unsaidtalks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.7.2",
    "anthropic>=0.57.1",
    "exa-py>=1.14.16",
    "google-genai>=1.25.0",
    "openai>=1.95.0",
    "yfinance>=0.2.65",
]
